name: Build and deploy fn-powerapps-api-sloojb3imt3xy (OIDC)
on:
  workflow_dispatch:    
permissions:
      id-token: write
env:
  AZURE_FUNCTIONAPP_NAME: fn-powerapps-api-sloojb3imt3xy
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ./.
  WORKING_DIRECTORY: ./src
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 3.1.x
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Installing Az.accounts for powershell
      shell: pwsh
      run: |
           Install-Module -Name Az.Accounts -Force -AllowClobber -Repository PSGallery

    - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
      uses: azure/login@v1.4.0
      with:
        client-id: ${{ secrets.AZURE_CLIENTID }}
        tenant-id: ${{ secrets.AZURE_TENANTID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }} 
        enable-AzPSSession: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
        
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }}

    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with: # Set Azure credentials secret as an input
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
